[package]
name = "settlement_starknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.9.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.44.0" }

[scripts]
test = "snforge test"

[[target.starknet-contract]]
sierra = true
casm = true

[tool.snforge]

