[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
bankai_solana = "HpgNxwdekXixEW6ZzTPsjhhFx46fpfoC7ruJvsinPYHx"

[programs.devnet]
bankai_solana = "HpgNxwdekXixEW6ZzTPsjhhFx46fpfoC7ruJvsinPYHx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
